OPENAI_API_KEY = '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'
PATH_TO_GITREPO_DIR = './gitRepo/'
DATABASE_USER = 'root'
DATABASE_PSW = '111'
DATABASE_DBNAME = 'test'
DATABASE_PORT = 6001
DATABASE_HOST = '127.0.0.1'
LLM_MODEL_NAME = 'gpt-3.5-turbo'
